spring:
  main:
    banner_mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/movieLand
    username: hbstudent
    password: hbstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftlh

  thymeleaf:
    enabled: false
#  data:
#    rest:
#      base-path: /api
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *

logging:
  level:
    org:
      hibernate:
        SQL: debug


